import { SignIn, SignUp } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { dark } from "@clerk/themes";

const SignInPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>SoldOut - Sign In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex justify-center items-center bg-gray-800">
        <SignIn 
            appearance={{
                baseTheme: dark,
            }}
        path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </div>
    </>
  );
};

export default SignInPage;

