import { SignIn, SignUp } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { dark } from "@clerk/themes";

const SignUpPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>SoldOut - Sign Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex justify-center items-center">
        <SignUp appearance={{
                baseTheme: dark,
            }} path="/sign-in" routing="path" signInUrl="/sign-up" />
      </div>
    </>
  );
};

const styles = {
  width: "100vw",
  height: "100vh",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
};

export default SignUpPage;
